### ISSUE TITLE
thread-safe or not?

### ISSUE THREAD

**Issue by petamem** [jonathanstowe/TermReadKey#17]
Could you please confirm that Term::ReadKey is or is not thread-safe?
I experience quite a lot of crashes of Term::ReadKey 2.33 in a forking environment under Windows.

**Comment by jonathanstowe** [comment]
The module is not designed with thread safety in mind, (it pre-dates threading in Perl and fork emulation on Windows,) so it would be fairly safe to assume it won't play nicely in a threaded environment.

Specifically the XS parts of the module make calls to functions in the system C library which are probably not re-entrant in most implementations, and there are several static "global" variables in the XS code itself that are used to retain state which would also militate against its being "thread-safe"..

While it would be theoretically possible to make a module that does what Term::ReadKey does in a more thread-safe manner, it would almost certainly have to be a new and separate module as it would need a completely different interface style

**Comment by jonathanstowe** [comment]
I'm going to close this as I guess the above answers the question.
