### ISSUE TITLE
CPAN Pull Request Challenge

### ISSUE THREAD

**Issue by sdeseille** [jonathanstowe/TermReadKey#4]
Hi Jonathan

I joined the "CPAN Pull Request Challenge" and Neil Bowers ask me to make a Pull Request on your module "Term::ReadKey".

Neil advised me to work on test suite.

Will you accept that i submit a patch in order to reorganize tests suite ?

I already fork your repository and make a branch to work on.
I tried my branch on Win32 system and Linux system and result seem clean.
...
All tests successful.
Files=2, Tests=8,  1 wallclock secs ( 0.07 usr  0.03 sys +  0.15 cusr  0.02 csys =  0.27 CPU)
Result: PASS

regards

sdeseille

**Comment by jonathanstowe** [comment]
Hi,
Feel free. Obviously whether the changes actually get released is contingent upon the tests passing on at least FreeBSD as well.

Thanks for the help and keep up the good work.

**Comment by sdeseille** [comment]
Hi Again

Thank you.
I tested with FreeBSD 10.1 amd64 with my vagrant box.

Here the result:
[vagrant@vagrant-freebsd-101-amd64 ~/TermReadKey]$ perl Makefile.PL
Checking if your kit is complete...
Looks good
Writing Makefile for Term::ReadKey
Writing MYMETA.yml and MYMETA.json
[vagrant@vagrant-freebsd-101-amd64 ~/TermReadKey]$ make test
Smartmatch is experimental at /usr/local/lib/perl5/5.18/BSDPAN/ExtUtils/Packlist.pm line 218.
cp ReadKey.pm blib/lib/Term/ReadKey.pm
AutoSplitting blib/lib/Term/ReadKey.pm (blib/lib/auto/Term/ReadKey)
/usr/local/bin/perl5.18.4 -Mblib -I/usr/local/lib/perl5/5.18 genchars.pl

Writing termio/termios section of cchars.h... Done.
Checking for sgtty...
        Sgtty NOT found.
Writing sgtty section of cchars.h... Done.
/usr/local/bin/perl5.18.4 /usr/local/lib/perl5/5.18/ExtUtils/xsubpp -noprototypes -typemap /usr/local/lib/perl5/5.18/ExtUtils/typemap  ReadKey.xs > ReadKey.xsc && mv ReadKey.xsc ReadKey.c
cc -c    -DAPPLLIB_EXP="/usr/local/lib/perl5/5.18/BSDPAN" -DHAS_FPSETMASK -DHAS_FLOATINGPOINT_H -fno-strict-aliasing -pipe -fstack-protector -I/usr/local/include -O2 -pipe -fstack-protector -fno-strict-aliasing    -DVERSION=\"2.32\"  -DXS_VERSION=\"2.32\" -DPIC -fPIC "-I/usr/local/lib/perl5/5.18/mach/CORE"   ReadKey.c
Running Mkbootstrap for Term::ReadKey ()
chmod 644 ReadKey.bs
rm -f blib/arch/auto/Term/ReadKey/ReadKey.so
cc  -shared  -L/usr/local/lib -fstack-protector ReadKey.o  -o blib/arch/auto/Term/ReadKey/ReadKey.so
chmod 755 blib/arch/auto/Term/ReadKey/ReadKey.so
cp ReadKey.bs blib/arch/auto/Term/ReadKey/ReadKey.bs
chmod 644 blib/arch/auto/Term/ReadKey/ReadKey.bs
PERL_DL_NONLAZY=1 /usr/local/bin/perl5.18.4 "-MExtUtils::Command::MM" "-e" "test_harness(0, 'blib/lib', 'blib/arch')" t/*.t
t/01_basic.t ............... ok
t/02_terminal_functions.t .. ok
All tests successful.
Files=2, Tests=8,  0 wallclock secs ( 0.08 usr  0.02 sys +  0.17 cusr  0.03 csys =  0.30 CPU)
Result: PASS

**Comment by jonathanstowe** [comment]
All good:

https://travis-ci.org/jonathanstowe/TermReadKey/builds/58234692

**Comment by sdeseille** [comment]
Great I close.
